[2025-02-13T05:49:07.290+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-13T05:49:07.324+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: workflow_1.upload_data_to_s3 manual__2025-02-13T05:48:50.714779+00:00 [queued]>
[2025-02-13T05:49:07.347+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: workflow_1.upload_data_to_s3 manual__2025-02-13T05:48:50.714779+00:00 [queued]>
[2025-02-13T05:49:07.348+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-02-13T05:49:07.393+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): upload_data_to_s3> on 2025-02-13 05:48:50.714779+00:00
[2025-02-13T05:49:07.401+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'workflow_1', 'upload_data_to_s3', 'manual__2025-02-13T05:48:50.714779+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/retry.py', '--cfg-path', '/tmp/tmp58dy5ucy']
[2025-02-13T05:49:07.403+0000] {standard_task_runner.py:105} INFO - Job 31: Subtask upload_data_to_s3
[2025-02-13T05:49:07.405+0000] {logging_mixin.py:190} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=555) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-02-13T05:49:07.406+0000] {standard_task_runner.py:72} INFO - Started process 565 to run task
[2025-02-13T05:49:07.507+0000] {task_command.py:467} INFO - Running <TaskInstance: workflow_1.upload_data_to_s3 manual__2025-02-13T05:48:50.714779+00:00 [running]> on host f6cd8c636678
[2025-02-13T05:49:07.658+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='workflow_1' AIRFLOW_CTX_TASK_ID='upload_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-02-13T05:48:50.714779+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-13T05:48:50.714779+00:00'
[2025-02-13T05:49:07.659+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-02-13T05:49:07.696+0000] {base.py:84} INFO - Retrieving connection 's3_conn'
[2025-02-13T05:49:07.697+0000] {connection_wrapper.py:325} INFO - AWS Connection (conn_id='s3_conn', conn_type='aws') credentials retrieved from login and password.
[2025-02-13T05:49:22.971+0000] {hook.py:208} WARNING - Data lineage tracking is disabled. Register a hook lineage reader to start tracking hook lineage.
[2025-02-13T05:49:22.973+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-13T05:49:23.000+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-02-13T05:49:23.001+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=workflow_1, task_id=upload_data_to_s3, run_id=manual__2025-02-13T05:48:50.714779+00:00, execution_date=20250213T054850, start_date=20250213T054907, end_date=20250213T054923
[2025-02-13T05:49:23.123+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-13T05:49:23.160+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-13T05:49:23.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
